apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-app-binary-task
spec:
  workspaces:
    - name: source
      description: The workspace where the repository will be cloned
  steps:
    - name: build-app-binary
      image: quay.io/djodha/golang:1.23.0-alpine
      script: |
        cd $(workspaces.source.path)
        go build -o app-binary .
        echo "Successfully built the Golang application binary"
