apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: list-files-task
spec:
  steps:
    - name: list-files
      image: quay.io/djodha/alpine-git:1.0.0
      workingDir: /workspace
      script: |
        ls -l /workspace
