apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-ui-tests-task
spec:
  steps:
    - name: run-ui-tests
      image:  quay.io/djodha/cypress:1.0.0
      script: |
        cd /workspace
        npm install  # Install dependencies
        ./app-binary &
        sleep 20
        export NO_COLOR=1
        cypress run --spec cypress/e2e/spec.cy.js
        echo "Finished running UI tests"
