apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-test-task
spec:
  steps:
    - name: checkout-source
      image: alpine/git
      script: |
        git clone https://github.com/dheerajodha/the-mentalist-quiz.git /workspace
    - name: list-files
      image: alpine
      script: |
        ls -l /workspace
    - name: run-tests
      image: golang:1.21
      workingDir: /workspace
      script: |
        go test ./... > tests.log
        cat tests.log
