apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-test-task
spec:
  steps:
    - name: checkout-source
      image: alpine/git
      script: |
        git clone https://github.com/dheerajodha/the-mentalist-quiz.git /workspace
    - name: list-files
      image: alpine
      script: |
        ls -l /workspace
    - name: run-unit-tests
      image: golang:1.21
      workingDir: /workspace
      script: |
        go test ./... > tests.log
        cat tests.log
    - name: start-application
      image: golang:1.21
      workingDir: /workspace
      script: |
        # Start the application
        go build -o app-binary .
    - name: run-ui-tests
      image: cypress/included:13.13.0
      workingDir: /workspace
      script: |
        ./app-binary &
        sleep 30
        # To prevent Tekton logs flooded by ANSI escape codes for coloured text
        export NO_COLOR=1
        # Run Cypress tests
        cypress run --spec cypress/e2e/spec.cy.js
