---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: extract-image-from-snapshot
  labels:
    app.kubernetes.io/version: "2.1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task that extracts image url to be released on github.com from the snapshot
  params:
    - name: snapshotPath
      type: string
      description: Path to the JSON string of the mapped Snapshot spec in the data workspace
    - name: subdirectory
      description: Subdirectory inside the workspace to be used for storing the snapshotSpec
      type: string
      default: ""
  results:
    - name: image_url
      type: string
      description: The container URL of the image built by Konflux
  workspaces:
    - name: data
      description: The workspace where the snapshot is stored.
  steps:
    - name: extract-image-from-snapshot
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      script: |
        #!/bin/sh -ex

        SNAPSHOT_SPEC_FILE="$(workspaces.data.path)/$(params.snapshotPath)"
        if [ ! -f "${SNAPSHOT_SPEC_FILE}" ] ; then
            echo "Error: No valid snapshot file was provided."
            exit 1
        fi

        NUM_COMPONENTS=$(jq '.components | length' "$SNAPSHOT_SPEC_FILE")
        for ((i=0; i < NUM_COMPONENTS; i++)); do
          COMPONENT=$(jq -c ".components[$i]" "$SNAPSHOT_SPEC_FILE")
          COMPONENT_NAME=$(echo $COMPONENT | jq -r '.name')

          IMAGE_URL=$(echo $COMPONENT | jq -r '.containerImage // ""')
          if [ -z "${IMAGE_URL}" ] ; then
              echo "Error: Unable to get image url from snapshot."
              exit 1
          fi
        done

        echo -n $IMAGE_URL | tee $(results.image_url.path)
