apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: go-test-pipelinerun
  labels:
    appstudio.openshift.io/component: the-mentalist-quiz
spec:
  pipelineRef:
    resolver: git
    params:
    - name: url 
      value: https://github.com/dheerajodha/the-mentalist-quiz
    - name: revision
      value: main
    - name: pathInRepo
      value: integration-tests/pipelines/test-pipeline.yaml
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: my-pvc
