apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: go-test-pipelinerun
spec:
  pipelineRef:
    resolver: git
    params:
    - name: url 
      value: https://github.com/dheerajodha/the-mentalist-quiz
    - name: revision
      value: ui-tests
    - name: pathInRepo
      value: integration-tests/pipelines/test-pipeline.yaml
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: my-pvc
