apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: go-test-pipeline
spec:
  workspaces:
    - name: source
  tasks:
    - name: my-task
      taskRef:
        resolver: git
        params:
        - name: url 
          value: https://github.com/dheerajodha/the-mentalist-quiz
        - name: revision
          value: main
        - name: pathInRepo
          value: integration-tests/task/test-task.yaml
      workspaces:
        - name: source
          workspace: source
