apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: go-test-pipeline
spec:
  workspaces:
    - name: source
  tasks:
    - name: my-task
      taskRef:
        name: go-test-task
      workspaces:
        - name: source
          workspace: source
