apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: go-test-pipeline
spec:
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
  tasks:
    - name: test-metadata
      taskRef:
        resolver: git
        params:
        - name: url 
          value: https://github.com/dirgim/integration-examples
        - name: revision
          value: test-metadata
        - name: pathInRepo
          value: tasks/test_metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
    - name: go-test-task
      taskRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/dheerajodha/the-mentalist-quiz
        - name: revision
          value: main
        - name: pathInRepo
          value: integration-tests/task/test-task.yaml
      params:
        - name: source-git-url
          value: $(tasks.test-metadata.results.source-git-url)
        - name: source-git-revision
          value: $(tasks.test-metadata.results.source-git-revision)
      runAfter:
        - test-metadata
